In [1]:
import csv

In [2]:
open_price = {}
close_price = {}
high_price = {}
low_price = {}
volume = {}
ma_15days = {}
rsi = {}
daily_return = {}
macd = {}
signal = {}
for i in range(1,10000):
    if i < 10:
        string = "000" + str(i) + ".HK.csv"
    elif i < 100:
        string = "00" + str(i) + ".HK.csv"
    elif i < 1000:
        string = "0" + str(i) + ".HK.csv"
    else:
        string = str(i) + ".HK.csv"
    try :
        open(string)
    except FileNotFoundError:
        continue
    with open(string) as csv_file:
        csv_reader = csv.reader(csv_file, delimiter=',')
        next(csv_reader)
        open_price[i] = []
        close_price[i] = []
        high_price[i] = []
        low_price[i] = []
        volume[i] = []
        ma_15days[i] = []
        rsi[i] = []
        daily_return[i] = []
        macd[i] = []
        signal[i] = []
        for row in csv_reader:
            open_price[i].append(row[3])
            close_price[i].append(row[2])
            high_price[i].append(row[4])
            low_price[i].append(row[5])
            volume[i].append(row[7])
            daily_return[i].append(row[9])
            ma_15days[i].append(row[16])
            rsi[i].append(row[17])
            macd[i].append(row[24])
            signal[i].append(row[25])
        daily_return[0] = 0
        for j in range(15):
            ma_15days[j] = 0
            rsi[j] = 0
        for j in range(25):
            macd[j] = 0
        for j in range(33):
            signal[j] = 0
        for j in range(len(open_price)):
            open_price[i][j] = float(open_price[i][j])
            close_price[i][j] = float(close_price[i][j])
            high_price[i][j] = float(high_price[i][j])
            low_price[i][j] = float(low_price[i][j])
            volume[i][j] = float(volume[i][j])
            daily_return[i][j] = float(daily_return[i][j])
            ma_15days[i][j] = float(ma_15days[i][j])
            rsi[i][j] = float(rsi[i][j])
            macd[i][j] = float(macd[i][j])
            signal[i][j] = float(signal[i][j])


1.045142857


In [3]:
# store different length of rsi14 value
rsi_dict = {}
for i in range(1,51):
    rsi_collection = []
    for j in range(len(rsi)):
        daily_value = []
        for k in range((j-i if (j-i) > 0 else 0),j):
            daily_value.append(rsi[k])
        rsi_collection.append(daily_value)
    rsi_dict[i] = rsi_collection
print(rsi_dict[10])

[[], [0.0], [0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 47.10884354], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 47.10884354, 39.1221374], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 47.10884354, 39.1221374, 32.55813953], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 47.10884354, 39.1221374, 32.55813953, 33.12368973], [0.0, 0.0, 0.0, 0.0, 0.0, 47.10884354, 39.1221374, 32.55813953, 33.12368973, 62.52285192], [0.0, 0.0, 0.0, 0.0, 47.10884354, 39.1221374, 32.55813953, 33.12

In [4]:
# store different length of macd value
macd_dict = {}
for i in range(1,51):
    macd_collection = []
    for j in range(len(rsi)):
        daily_value = []
        for k in range((j-i if (j-i) > 0 else 0),j):
            daily_value.append(macd[k])
        macd_collection.append(daily_value)
    macd_dict[i] = macd_collection
print(macd_dict[10])

[[], [0.0], [0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0

In [5]:
signal_dict = {}
for i in range(1,51):
    signal_collection = []
    for j in range(len(signal)):
        daily_value = []
        for k in range((j-i if (j-i) > 0 else 0),j):
            daily_value.append(signal[k])
        signal_collection.append(daily_value)
    signal_dict[i] = signal_collection
print(signal_dict[10])

[[], [0.0], [0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0

In [6]:
# Store different windows of daily return
one_day_return = {}
five_day_return = {}
ten_day_return = {}
for i in range(len(daily_return)):
    one_day_return[i] = daily_return[i]
for i in range(len(daily_return)):
    five_day_actual_return = 1
    for j in range(5):
        five_day_actual_return = five_day_actual_return * (1 + daily_return[(i+j) if (i+j) <= len(daily_return) - 1 else len(daily_return) - 1])
    five_day_return[i] = five_day_actual_return
for i in range(len(daily_return)):
    ten_day_actual_return = 1
    for j in range(10):
        ten_day_actual_return = ten_day_actual_return * (1 + daily_return[(i+j) if (i+j) <= len(daily_return) - 1 else len(daily_return) - 1])
    ten_day_return[i] = ten_day_actual_return
print(ten_day_return)

{0: 0.9885181700184561, 1: 0.967195042276622, 2: 0.9850496960691157, 3: 0.9483491582120804, 4: 0.9191400341080684, 5: 0.8689174082628739, 6: 0.9326313976769355, 7: 0.9671050486519202, 8: 0.9862180922235453, 9: 1.0363533074541087, 10: 1.1266590624442274, 11: 1.0989256987472484, 12: 1.058459582641822, 13: 1.0555865544302663, 14: 1.025055505555686, 15: 1.080571326132749, 16: 1.029909603998097, 17: 1.0260770008165023, 18: 1.0162101238146721, 19: 0.9762546466176966, 20: 0.9111437930250789, 21: 0.9423868408093593, 22: 0.9989378501491242, 23: 0.976595772770044, 24: 1.009234189773431, 25: 0.9645690867471461, 26: 1.0427398386887694, 27: 1.0342542449324945, 28: 1.1039605084561734, 29: 1.0525152905237376, 30: 1.030711308404593, 31: 1.014738070653702, 32: 0.9803296671276414, 33: 0.9760348344038866, 34: 0.9779332162185121, 35: 0.9989034264237148, 36: 0.959537506257562, 37: 0.9871794581313598, 38: 0.927254538781488, 39: 0.9716386044916095, 40: 0.9822268317530254, 41: 1.0053791630305458, 42: 1.002711

In [7]:
# Calculate the correlation of different length window of rsi and macd value to the 1-day, 5-day, 10-day stock return

In [8]:
import numpy as np

In [9]:
average_macd_list = []
for i in range (len(macd_dict[10])):
    average_macd_list.append(sum(macd_dict[10][i])/10)
y_list = list(ten_day_return.values())
x_axis = []
y_axis = []
for i in range(100,600):
    x_axis.append(average_macd_list[i])
    y_axis.append(y_list[i])
x_axis = np.array(x_axis)
y_axis = np.array(y_axis)
r = np.corrcoef(x_axis, y_axis)
print(r)

[[1.         0.02501921]
 [0.02501921 1.        ]]


In [10]:
average_macd_list_five = []
for i in range (len(macd_dict[5])):
    average_macd_list_five.append(sum(macd_dict[5][i])/5)
y_list = list(five_day_return.values())
x_axis = []
y_axis = []
for i in range(100,600):
    x_axis.append(average_macd_list_five[i])
    y_axis.append(y_list[i])
x_axis = np.array(x_axis)
y_axis = np.array(y_axis)
r = np.corrcoef(x_axis, y_axis)
print(r)

[[1.         0.00382163]
 [0.00382163 1.        ]]


In [11]:
average_signal_list = []
for i in range (len(signal_dict[10])):
    average_signal_list.append(sum(signal_dict[10][i])/10)
y_list = list(ten_day_return.values())
x_axis = []
y_axis = []
for i in range(100,600):
    x_axis.append(average_signal_list[i])
    y_axis.append(y_list[i])
x_axis = np.array(x_axis)
y_axis = np.array(y_axis)
r = np.corrcoef(x_axis, y_axis)
print(r)

[[ 1.00000000e+00 -2.58840253e-04]
 [-2.58840253e-04  1.00000000e+00]]


In [12]:
average_signal_list_five = []
for i in range (len(signal_dict[5])):
    average_signal_list_five.append(sum(signal_dict[5][i])/5)
y_list = list(five_day_return.values())
x_axis = []
y_axis = []
for i in range(100,600):
    x_axis.append(average_signal_list_five[i])
    y_axis.append(y_list[i])
x_axis = np.array(x_axis)
y_axis = np.array(y_axis)
r = np.corrcoef(x_axis, y_axis)
print(r)

[[1.         0.01002919]
 [0.01002919 1.        ]]


In [13]:
average_rsi_list = []
for i in range (len(rsi_dict[10])):
    average_rsi_list.append(sum(rsi_dict[10][i])/10)
y_list = list(ten_day_return.values())
x_axis = []
y_axis = []
for i in range(100,600):
    x_axis.append(average_rsi_list[i])
    y_axis.append(y_list[i])
x_axis = np.array(x_axis)
y_axis = np.array(y_axis)
r = np.corrcoef(x_axis, y_axis)
print(r)

[[1.         0.11398045]
 [0.11398045 1.        ]]


In [14]:
average_rsi_list_five = []
for i in range (len(rsi_dict[5])):
    average_rsi_list_five.append(sum(rsi_dict[5][i])/5)
y_list = list(five_day_return.values())
x_axis = []
y_axis = []
for i in range(100,600):
    x_axis.append(average_rsi_list_five[i])
    y_axis.append(y_list[i])
x_axis = np.array(x_axis)
y_axis = np.array(y_axis)
r = np.corrcoef(x_axis, y_axis)
print(r)

[[1.         0.07211509]
 [0.07211509 1.        ]]


In [15]:
from sklearn.linear_model import LinearRegression

In [16]:
macd_curve = []
new_daily_return = daily_return[33:900]
for i in range(33,900):
    macd_curve.append(macd[i]-signal[i])
print(len(macd_curve))
print(len(new_daily_return))

867
867


In [17]:
x_axis = np.array(macd_curve).reshape(-1,1)
y_axis = np.array(new_daily_return)

In [20]:
model = LinearRegression()
model.fit(x_axis, y_axis)
r_sq = model.score(x_axis, y_axis)

In [24]:
print('alpha:', model.intercept_)
print('beta:', float(model.coef_))
print('r squared value:', r_sq)

alpha: -0.00044545662544188567
beta: 0.6865577479016101
r squared value: 0.029305733493746766


In [23]:
class sklearn.linear_model.LinearRegression(*, fit_intercept=True, normalize=False, copy_X=True, n_jobs=None)

SyntaxError: invalid syntax (<ipython-input-23-6aa82f47f08e>, line 1)