In [2]:
import csv

In [34]:
with open("0001.HK.csv") as csv_file:
    csv_reader = csv.reader(csv_file, delimiter=',')
    next(csv_reader)
    open_price = []
    close_price = []
    high_price = []
    low_price = []
    volume = []
    ma_15days = []
    rsi = []
    daily_return = []
    macd = []
    signal = []
    for row in csv_reader:
        open_price.append(row[3])
        close_price.append(row[2])
        high_price.append(row[4])
        low_price.append(row[5])
        volume.append(row[7])
        daily_return.append(row[9])
        ma_15days.append(row[16])
        rsi.append(row[17])
        macd.append(row[24])
        signal.append(row[25])
    daily_return[0] = 0
    for i in range(15):
        ma_15days[i] = 0
        rsi[i] = 0
    for i in range(25):
        macd[i] = 0
    for i in range(33):
        signal[i] = 0
    for i in range(len(open_price)):
        open_price[i] = float(open_price[i])
        close_price[i] = float(close_price[i])
        high_price[i] = float(high_price[i])
        low_price[i] = float(low_price[i])
        volume[i] = float(volume[i])
        daily_return[i] = float(daily_return[i])
        ma_15days[i] = float(ma_15days[i])
        rsi[i] = float(rsi[i])
        macd[i] = float(macd[i])
        signal[i] = float(signal[i])
print(close_price[0])

107.400002


# We will first see correlation between different indicators and the return in t+1, t+2, ...

In [47]:
for j in range(1,21):
    x_axis = []
    y_axis = []
    for i in range(100,600):
        x_axis.append(rsi[i])
        y_axis.append(daily_return[i+j])
    x_axis = np.array(x_axis)
    y_axis = np.array(y_axis)
    r = round(np.corrcoef(x_axis, y_axis)[0][1],4)
    print("Corr( RSI, RET(t +",j,") )=",r)

Corr( RSI, RET(t + 1 ) )= 0.0377
Corr( RSI, RET(t + 2 ) )= 0.0212
Corr( RSI, RET(t + 3 ) )= 0.024
Corr( RSI, RET(t + 4 ) )= 0.0349
Corr( RSI, RET(t + 5 ) )= 0.0318
Corr( RSI, RET(t + 6 ) )= 0.0348
Corr( RSI, RET(t + 7 ) )= 0.0467
Corr( RSI, RET(t + 8 ) )= 0.0312
Corr( RSI, RET(t + 9 ) )= 0.0138
Corr( RSI, RET(t + 10 ) )= -0.0099
Corr( RSI, RET(t + 11 ) )= -0.0455
Corr( RSI, RET(t + 12 ) )= -0.0604
Corr( RSI, RET(t + 13 ) )= -0.0565
Corr( RSI, RET(t + 14 ) )= -0.0452
Corr( RSI, RET(t + 15 ) )= -0.0483
Corr( RSI, RET(t + 16 ) )= -0.0388
Corr( RSI, RET(t + 17 ) )= -0.0587
Corr( RSI, RET(t + 18 ) )= -0.0502
Corr( RSI, RET(t + 19 ) )= -0.0336
Corr( RSI, RET(t + 20 ) )= -0.0485


In [36]:
for j in range(1,21):
    x_axis = []
    y_axis = []
    for i in range(100,600):
        x_axis.append(macd[i]-signal[i])
        y_axis.append(daily_return[i+j])
    x_axis = np.array(x_axis)
    y_axis = np.array(y_axis)
    r = round(np.corrcoef(x_axis, y_axis)[0][1],4)
    print("The correlation of macd histogram with return in t +",j,"is",r)

The correlation of macd histogram with return in t + 1 is 0.0124
The correlation of macd histogram with return in t + 2 is 0.007
The correlation of macd histogram with return in t + 3 is 0.0255
The correlation of macd histogram with return in t + 4 is 0.0394
The correlation of macd histogram with return in t + 5 is 0.0413
The correlation of macd histogram with return in t + 6 is 0.0512
The correlation of macd histogram with return in t + 7 is 0.0572
The correlation of macd histogram with return in t + 8 is 0.0586
The correlation of macd histogram with return in t + 9 is 0.0407
The correlation of macd histogram with return in t + 10 is 0.0154
The correlation of macd histogram with return in t + 11 is 0.0065
The correlation of macd histogram with return in t + 12 is 0.0142
The correlation of macd histogram with return in t + 13 is 0.0191
The correlation of macd histogram with return in t + 14 is 0.0037
The correlation of macd histogram with return in t + 15 is -0.0066
The correlation of 

In [37]:
for j in range (1,12):
    
    average_macd_list = []
    for i in range (len(macd_dict[j])):
        average_macd_list.append(sum(macd_dict[j][i])/j) #storing macd average of 10 lookback days
    y_list = list(ten_day_return.values()) #storing ten-day returns
    x_axis = []
    y_axis = []
    for i in range(100,600): #run a regression of the above two sets of data using by taking samples of index number 100 to 599
        x_axis.append(average_macd_list[i])
        y_axis.append(y_list[i])
    x_axis = np.array(x_axis)
    y_axis = np.array(y_axis)
    r = round(np.corrcoef(x_axis, y_axis)[0][1],4)
    print("The correlation between ",j ," days average macd and 10-day return is " , r)

The correlation between  1  days average macd and 10-day return is  -0.1646
The correlation between  2  days average macd and 10-day return is  -0.169
The correlation between  3  days average macd and 10-day return is  -0.175
The correlation between  4  days average macd and 10-day return is  -0.1827
The correlation between  5  days average macd and 10-day return is  -0.1918
The correlation between  6  days average macd and 10-day return is  -0.2015
The correlation between  7  days average macd and 10-day return is  -0.2116
The correlation between  8  days average macd and 10-day return is  -0.2215
The correlation between  9  days average macd and 10-day return is  -0.2309
The correlation between  10  days average macd and 10-day return is  -0.2395
The correlation between  11  days average macd and 10-day return is  -0.2468


# In the following we will first store the data of indicators with different lookback periods

In [38]:
# store different length of rsi14 value
rsi_dict = {}
for i in range(1,51): #iterate through 1 to 50 lookback periods
    rsi_collection = []
    for j in range(51,len(rsi)-1): #iterate through the first date to the last
        daily_value = []
        for k in range(j-i,j): #this would create a list with the length of lookback period
            daily_value.append(rsi[k])
        rsi_collection.append(daily_value)
    rsi_dict[i] = rsi_collection #rsi_dict[i] would store the data of rsi with lookback period of i days
#print(rsi_dict[10]) #display a number of lists that contain 10 rsi data back

In [39]:
# store different length of macd value
macd_dict = {}
for i in range(1,51):
    macd_collection = []
    for j in range(51,len(macd)-1):
        daily_value = []
        for k in range(j-i ,j):
            daily_value.append(macd[k])
        macd_collection.append(daily_value)
    macd_dict[i] = macd_collection
#print(macd_dict[10])

In [40]:
signal_dict = {}
for i in range(1,51):
    signal_collection = []
    for j in range(51,len(signal)-1):
        daily_value = []
        for k in range(j-i,j):
            daily_value.append(signal[k])
        signal_collection.append(daily_value)
    signal_dict[i] = signal_collection
#print(signal_dict[10])

In [41]:
# Store different windows of daily return
one_day_return = {}
five_day_return = {}
ten_day_return = {}
for i in range(52,len(daily_return)):
    one_day_return[i] = daily_return[i]
for i in range(52,len(daily_return)):
    five_day_actual_return = 1
    for j in range(5):
        five_day_actual_return = five_day_actual_return * (1 + daily_return[(i+j) if (i+j) <= len(daily_return) - 1 else len(daily_return) - 1])
    five_day_return[i] = five_day_actual_return
for i in range(52,len(daily_return)):
    ten_day_actual_return = 1
    for j in range(10):
        ten_day_actual_return = ten_day_actual_return * (1 + daily_return[(i+j) if (i+j) <= len(daily_return) - 1 else len(daily_return) - 1])
    ten_day_return[i] = ten_day_actual_return
#print(ten_day_return)

# Calculate the correlation of different length window of rsi and macd value to the 1-day, 5-day, 10-day stock return

In [42]:
import numpy as np

In [9]:
#to see how the average of macd corrlates with 10-day return data
average_macd_list = []
for i in range (len(macd_dict[10])):
    average_macd_list.append(sum(macd_dict[10][i])/10) #storing macd average of 10 lookback days
y_list = list(ten_day_return.values()) #storing ten-day returns
x_axis = []
y_axis = []
for i in range(100,600): #run a regression of the above two sets of data using by taking samples of index number 100 to 599
    x_axis.append(average_macd_list[i])
    y_axis.append(y_list[i])
x_axis = np.array(x_axis)
y_axis = np.array(y_axis)
r = round(np.corrcoef(x_axis, y_axis)[0][1],4)
print("The correlation is " , r)

The correlation is  -0.2395


In [11]:
average_macd_list_five = []
for i in range (len(macd_dict[5])):
    average_macd_list_five.append(sum(macd_dict[5][i])/5)
y_list = list(five_day_return.values())
x_axis = []
y_axis = []
for i in range(100,600):
    x_axis.append(average_macd_list_five[i])
    y_axis.append(y_list[i])
x_axis = np.array(x_axis)
y_axis = np.array(y_axis)
r = round(np.corrcoef(x_axis, y_axis)[0][1],4)
print("The correlation between 5 days average macd and 5-day return is " , r)

The correlation between 5 days average macd and 5-day return is  -0.1028


In [12]:
average_signal_list = []
for i in range (len(signal_dict[10])):
    average_signal_list.append(sum(signal_dict[10][i])/10)
y_list = list(ten_day_return.values())
x_axis = []
y_axis = []
for i in range(100,600):
    x_axis.append(average_signal_list[i])
    y_axis.append(y_list[i])
x_axis = np.array(x_axis)
y_axis = np.array(y_axis)
r = round(np.corrcoef(x_axis, y_axis)[0][1],4)
print(r)

-0.2556


In [13]:
average_signal_list_five = []
for i in range (len(signal_dict[5])):
    average_signal_list_five.append(sum(signal_dict[5][i])/5)
y_list = list(five_day_return.values())
x_axis = []
y_axis = []
for i in range(100,600):
    x_axis.append(average_signal_list_five[i])
    y_axis.append(y_list[i])
x_axis = np.array(x_axis)
y_axis = np.array(y_axis)
r = np.corrcoef(x_axis, y_axis)
print(r)

[[ 1.         -0.13131592]
 [-0.13131592  1.        ]]


In [14]:
average_rsi_list = []
for i in range (len(rsi_dict[10])):
    average_rsi_list.append(sum(rsi_dict[10][i])/10)
y_list = list(ten_day_return.values())
x_axis = []
y_axis = []
for i in range(100,600):
    x_axis.append(average_rsi_list[i])
    y_axis.append(y_list[i])
x_axis = np.array(x_axis)
y_axis = np.array(y_axis)
r = np.corrcoef(x_axis, y_axis)
print(r)

[[ 1.         -0.12087886]
 [-0.12087886  1.        ]]


In [16]:
average_rsi_list_five = []
for i in range (len(rsi_dict[5])):
    average_rsi_list_five.append(sum(rsi_dict[5][i])/5)
y_list = list(five_day_return.values())
x_axis = []
y_axis = []
for i in range(100,600):
    x_axis.append(average_rsi_list_five[i])
    y_axis.append(y_list[i])
x_axis = np.array(x_axis)
y_axis = np.array(y_axis)
r = np.corrcoef(x_axis, y_axis)
print(r)

[[1.        0.0299568]
 [0.0299568 1.       ]]


In [17]:
from sklearn.linear_model import LinearRegression

In [18]:
macd_curve = []
new_daily_return = daily_return[33:900]
for i in range(33,900):
    macd_curve.append(macd[i]-signal[i])
print(len(macd_curve))
print(len(new_daily_return))

867
867


In [19]:
x_axis = np.array(macd_curve).reshape(-1,1)
y_axis = np.array(new_daily_return)

In [20]:
model = LinearRegression()
model.fit(x_axis, y_axis)
r_sq = model.score(x_axis, y_axis)

In [21]:
print('alpha:', model.intercept_)
print('beta:', float(model.coef_))
print('r squared value:', r_sq)

alpha: 0.00014656692622987008
beta: 0.021284616148906785
r squared value: 0.027964288169629925


In [22]:
#class sklearn.linear_model.LinearRegression(*, fit_intercept=True, normalize=False, copy_X=True, n_jobs=None)

In [23]:
from sklearn.linear_model import LinearRegression
#rsi_dict[50][i]
for i in range(21):
    model = LinearRegression().fit(rsi_dict[50][i], )

TypeError: fit() missing 1 required positional argument: 'y'